# Generated by Django 5.2 on 2025-05-09 20:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('psiu', 'Psiu'), ('estrela', 'Estrela')], max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('pagamento', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro')], max_length=20)),
                ('tipo_entrega', models.CharField(choices=[('retirar', 'Retirar no local'), ('entregar', 'Entregar em casa')], max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
