# Generated by Django 5.2 on 2025-05-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0002_pedido_data_criacao_itempedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='marca',
            field=models.CharField(choices=[('Psiu', 'Psiu'), ('Estrela', 'Estrela')], max_length=20),
        ),
    ]
