# Generated by Django 5.2 on 2025-05-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0003_alter_pedido_marca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
