# Generated by Django 5.2 on 2025-05-05 19:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=220)),
                ('foto', models.ImageField(blank=True, help_text='Foto de perfil do usuário', null=True, upload_to='perfil_fotos/')),
                ('cpf', models.CharField(help_text='CPF do usuário', max_length=14)),
                ('data_nascimento', models.DateField(default=datetime.date(2007, 1, 1), help_text='Data de nascimento do usuário')),
                ('cep', models.CharField(help_text='CEP do usuário', max_length=9)),
                ('endereco', models.CharField(blank=True, help_text='Endereço completo', max_length=220, null=True)),
                ('estado', models.CharField(blank=True, help_text='Estado da instalação (ex: PI)', max_length=2, null=True)),
                ('cidade', models.CharField(blank=True, help_text='Cidade do usuário', max_length=100, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
