# Generated by Django 5.2 on 2025-05-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='referencia',
            field=models.TextField(default='rua da paz'),
            preserve_default=False,
        ),
    ]
